# Development environment to mock the VM
services:
  vent:
    build:
      context: .
      dockerfile: ./vent/Dockerfile
    env_file: .env
    volumes:
      # Enable live code editing without rebuilding image
      - ./vent:/opt/vent/vent
      # Research storage volume
      - ./data:/mnt/data
